Optimize GitHub actions workflows

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -1,3 +1,4 @@
+---
 name: Terraform Preview
 
 on:
@@ -63,12 +64,12 @@ jobs:
 
       - name: List changed stacks
         id: list
-        run: terramate list -C stacks --changed
+        run: echo "changed_stacks=$(terramate -C stacks list --changed)" >> $GITHUB_OUTPUT
 
       ### Configure cloud credentials
 
       - name: Configure AWS credentials
-        if: steps.list.outputs.stdout
+        if: steps.list.outputs.changed_stacks
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-region: ${{ env.AWS_REGION }}
@@ -78,13 +79,13 @@ jobs:
           AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
 
       - name: Verify AWS credentials
-        if: steps.list.outputs.stdout
+        if: steps.list.outputs.changed_stacks
         run: aws sts get-caller-identity
 
       ### Run the Terraform preview via Terramate in each changed stack
 
       - name: Initialize Terraform in changed stacks
-        if: steps.list.outputs.stdout
+        if: steps.list.outputs.changed_stacks
         run: |
           terramate run \
             -C stacks \
@@ -94,7 +95,7 @@ jobs:
             terraform init -lock-timeout=5m
 
       - name: Validate Terraform configuration in changed stacks
-        if: steps.list.outputs.stdout
+        if: steps.list.outputs.changed_stacks
         run: |
           terramate run \
             -C stacks \
@@ -104,7 +105,7 @@ jobs:
             terraform validate
 
       - name: Plan Terraform changes in changed stacks
-        if: steps.list.outputs.stdout
+        if: steps.list.outputs.changed_stacks
         run: |
           terramate run \
             -C stacks \
@@ -122,51 +123,57 @@ jobs:
       ### Update Pull Request comment
 
       - name: Generate preview details
-        if: steps.list.outputs.stdout
+        if: steps.list.outputs.changed_stacks
         id: comment
         run: |
-          echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt "[:mag: View Details on Terramate Cloud]($(cat stacks/preview_url.txt))"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt "### Changed Stacks"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt '```bash'
-          echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
-          echo >>pr-comment.txt '```'
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt "#### Terraform Plan"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt '```terraform'
-          terramate run -C stacks --changed -- terraform show -no-color out.tfplan |& dd bs=1024 count=248 >>pr-comment.txt
-          [ "${PIPESTATUS[0]}" == "141" ] && sed -i 's/#### Terraform Plan/#### :warning: Terraform Plan truncated: please check console output :warning:/' pr-comment.txt
-          echo >>pr-comment.txt '```'
-          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
+          {
+            echo "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
+            echo
+            echo "[:mag: View Details on Terramate Cloud]($(cat stacks/preview_url.txt))"
+            echo
+            echo "### Changed Stacks"
+            echo
+            echo '```bash'
+            echo "${{ steps.list.outputs.changed_stacks }}"
+            echo '```'
+            echo
+            echo "#### Terraform Plan"
+            echo
+            echo '```terraform'
+            terramate run -C stacks --changed -- terraform show -no-color out.tfplan |& dd bs=1024 count=248
+            [ "${PIPESTATUS[0]}" == "141" ] && sed -i 's/#### Terraform Plan/#### :warning: Terraform Plan truncated: please check console output :warning:/' pr-comment.txt
+            echo '```'
+          } >> pr-comment.txt
+          cat pr-comment.txt >> $GITHUB_STEP_SUMMARY
 
       - name: Generate preview when no stacks changed
-        if: success() && !steps.list.outputs.stdout
+        if: success() && !steps.list.outputs.changed_stacks
         run: |
-          echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt "### Changed Stacks"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt 'No changed stacks, no detailed preview will be generated.'
-          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
+          {
+            echo "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
+            echo
+            echo "### Changed Stacks"
+            echo
+            echo 'No changed stacks, no detailed preview will be generated.'
+          } >> pr-comment.txt
+          cat pr-comment.txt >> $GITHUB_STEP_SUMMARY
 
       - name: Generate preview when things failed
         if: failure()
         run: |
-          echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt "[:mag: View Details on Terramate Cloud]($(cat stacks/preview_url.txt))"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt "### Changed Stacks"
-          echo >>pr-comment.txt
-          echo >>pr-comment.txt '```bash'
-          echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
-          echo >>pr-comment.txt '```'
-          echo >>pr-comment.txt ':boom: Generating preview failed. Please see details in Actions output.'
-          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
+          {
+            echo "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
+            echo
+            echo "[:mag: View Details on Terramate Cloud]($(cat stacks/preview_url.txt))"
+            echo
+            echo "### Changed Stacks"
+            echo
+            echo '```bash'
+            echo "${{ steps.list.outputs.changed_stacks }}"
+            echo '```'
+            echo ':boom: Generating preview failed. Please see details in Actions output.'
+          } >> pr-comment.txt
+          cat pr-comment.txt >> $GITHUB_STEP_SUMMARY
 
       - name: Publish generated preview as GitHub commnent
         uses: marocchino/sticky-pull-request-comment@v2
